Switch to AA2 SDK
digitalservicebund/useid-app-android pull request #166
Opened 2023-05-04 14:56 UTC by elaydis

2023-05-12 08:17 UTC, FabioTacke requested changes
Great work, @elaydis! Can't wait to get this thing merged. 😅

2023-05-12 13:16 UTC, elaydis commented on app/src/device/kotlin/de/digitalService/useID/idCardInterface/EidInteractionManager.kt
> +                    redirectUrl?.let { _eidFlow.value = EidInteractionEvent.AuthenticationSucceededWithRedirect(it) }
Let me know what you think about the change that I made, I rewrote it like 5 times and still don't love it, but not sure if there's a a real elegant way to deal with the result 🙃

2023-05-15 06:20 UTC, FabioTacke commented on app/src/device/kotlin/de/digitalService/useID/idCardInterface/EidInteractionManager.kt
> +                    redirectUrl?.let { _eidFlow.value = EidInteractionEvent.AuthenticationSucceededWithRedirect(it) }
That's way better now! 😃🙏

2023-05-15 06:21 UTC, FabioTacke approved these changes
🥳

2023-05-15 07:18 UTC, merged